package frontend.estadisticas;

import frontend.alumnos.DialogPerfilCompleto;
import frontend.auxiliares.TabbedPaneEntropy;
import frontend.inicio.VentanaPrincipal;
import javax.swing.UIManager;
import backend.Presentacion.Presentacion;
import backend.examenes.Examen;
import backend.gestores.GestorHistorialAlumno;
import backend.reporte.GestorGenerarReporteResolucion;
import backend.resoluciones.Resolucion;
import backend.usuarios.Alumno;
import frontend.auxiliares.CeldaMultiLineaRendererEntropy;
import frontend.auxiliares.LookAndFeelEntropy;
import java.awt.Desktop;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Denise
 */
public class PanelEstadisticasAlumno extends javax.swing.JPanel {

    private final Alumno alumno;
    private GestorHistorialAlumno gestorHistorial;

    /**
     * Creates new form PanelEstadisticasAlumno
     *
     * @param alumno cuyas estadísticas deben mostrarse.
     */
    public PanelEstadisticasAlumno(Alumno alumno) {
        initComponents();

        this.tbpSolapas.setUI(new TabbedPaneEntropy());
        this.alumno = alumno;
        this.lblAlumno.setText(alumno.getStrApellido() + ", " + alumno.getStrNombre());
        this.lblLegajo.setText((alumno.getStrLegajo() != null && !alumno.getStrLegajo().isEmpty()) ? alumno.getStrLegajo() : "---");
        gestorHistorial = new GestorHistorialAlumno();

        // Formato de tablas
        tblExamenesRendidos.getTableHeader().setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        tblExamenesRendidos.setDefaultRenderer(Object.class, new CeldaMultiLineaRendererEntropy(tblExamenesRendidos, false));
        tblClasesAsistidas.getTableHeader().setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        tblClasesAsistidas.setDefaultRenderer(Object.class, new CeldaMultiLineaRendererEntropy(tblClasesAsistidas, false));

        cargarExamenesRendidos();
        cargarClasesAsisitidas();
        ocultarColumnas();
    }

    private void cargarExamenesRendidos() {
        ArrayList<Resolucion> resolucion = gestorHistorial.getResoluciones(alumno.getIntAlumnoId());
        DefaultTableModel modeloTabla = (DefaultTableModel) tblExamenesRendidos.getModel();
        for (int i = 0; i < resolucion.size(); i++) {
            if (resolucion.get(i).getExamen()!= null) {
                modeloTabla.addRow(new Vector());
                Examen examen = gestorHistorial.getExamen(resolucion.get(i).getExamen().getIntExamenId());
                resolucion.get(i).setExamen(examen);
                modeloTabla.setValueAt(examen.getStrNombre(), i, 0);
                modeloTabla.setValueAt(String.format("%.2f", resolucion.get(i).getPorcentajeAprobacion()) + "%", i, 1);
                String fechaString = new SimpleDateFormat("dd-MM-yyyy").format(examen.getDteFecha());
                modeloTabla.setValueAt(fechaString, i, 2);
                modeloTabla.setValueAt(resolucion.get(i), i, 3);
            }
        }
        ocultarColumnas();
        tblExamenesRendidos.setModel(modeloTabla);
    }

    private void cargarClasesAsisitidas() {
        ArrayList<Presentacion> presentaciones = gestorHistorial.getAsistencias(alumno.getIntAlumnoId());
        DefaultTableModel modeloTabla = (DefaultTableModel) tblClasesAsistidas.getModel();
        for (int i = 0; i < presentaciones.size(); i++) {
            modeloTabla.addRow(new Vector());
            modeloTabla.setValueAt(presentaciones.get(i).getStrNombre(), i, 0);
            modeloTabla.setValueAt(presentaciones.get(i).getStrDescripcion(), i, 1);
            modeloTabla.setValueAt(new SimpleDateFormat("dd-MM-yyyy").format(presentaciones.get(i).getDteFecha()), i, 2);
            modeloTabla.setValueAt(presentaciones.get(i), i, 3);
        }
        tblClasesAsistidas.setModel(modeloTabla);
    }

    private void ocultarColumnas() {
        tblClasesAsistidas.getColumnModel().getColumn(3).setMaxWidth(0);
        tblClasesAsistidas.getColumnModel().getColumn(3).setMinWidth(0);
        tblClasesAsistidas.getColumnModel().getColumn(3).setPreferredWidth(0);
        tblExamenesRendidos.getColumnModel().getColumn(3).setMaxWidth(0);
        tblExamenesRendidos.getColumnModel().getColumn(3).setMinWidth(0);
        tblExamenesRendidos.getColumnModel().getColumn(3).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosExamen = new javax.swing.JPanel();
        upperSeparator = new javax.swing.JSeparator();
        lowerSeparator = new javax.swing.JSeparator();
        lblsAlumno = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        lblsLegajo = new javax.swing.JLabel();
        lblLegajo = new javax.swing.JLabel();
        lblPerfilCompleto = new javax.swing.JLabel();
        tbpSolapas = new javax.swing.JTabbedPane();
        pnlGeneral = new javax.swing.JPanel();
        lblsRendidos = new javax.swing.JLabel();
        lblRendidos = new javax.swing.JLabel();
        lblsAprobados = new javax.swing.JLabel();
        lblAprobados = new javax.swing.JLabel();
        lblsCorregidos = new javax.swing.JLabel();
        lblCorregidos = new javax.swing.JLabel();
        lblsPorcentajeAprobados = new javax.swing.JLabel();
        lblPorcentajeAprobados = new javax.swing.JLabel();
        lblsNotaPromedio = new javax.swing.JLabel();
        lblNotaPromedio = new javax.swing.JLabel();
        lblsNotaMayor = new javax.swing.JLabel();
        lblNotaMayor = new javax.swing.JLabel();
        lblsNotaMenor = new javax.swing.JLabel();
        lblNotaMenor = new javax.swing.JLabel();
        pnlHistograma = new javax.swing.JPanel();
        pnlRendimiento = new javax.swing.JPanel();
        pnlExamenes = new javax.swing.JPanel();
        scrExamenesRendidos = new javax.swing.JScrollPane();
        tblExamenesRendidos = new javax.swing.JTable();
        lblInfoExamenes = new javax.swing.JLabel();
        pnlAsistencias = new javax.swing.JPanel();
        scrClasesAsistidas = new javax.swing.JScrollPane();
        tblClasesAsistidas = new javax.swing.JTable();

        pnlDatosExamen.setBackground(LookAndFeelEntropy.COLOR_TABLA_PRIMARIO);
        pnlDatosExamen.setMaximumSize(new java.awt.Dimension(32767, 109));
        pnlDatosExamen.setName(""); // NOI18N

        upperSeparator.setForeground(LookAndFeelEntropy.COLOR_ENTROPY);

        lowerSeparator.setForeground(LookAndFeelEntropy.COLOR_ENTROPY);

        lblsAlumno.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsAlumno.setForeground(LookAndFeelEntropy.COLOR_FUENTE_TITULO_PANEL);
        lblsAlumno.setText("Alumno:");

        lblAlumno.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblAlumno.setText("Alumno");

        lblsLegajo.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsLegajo.setForeground(LookAndFeelEntropy.COLOR_FUENTE_TITULO_PANEL);
        lblsLegajo.setText("Legajo:");

        lblLegajo.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblLegajo.setText("---");

        lblPerfilCompleto.setFont(LookAndFeelEntropy.FUENTE_TITULO);
        lblPerfilCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_estadisticas_alumno_25x25.png"))); // NOI18N
        lblPerfilCompleto.setText("Ver perfil completo");
        lblPerfilCompleto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPerfilCompleto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerfilCompletoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosExamenLayout = new javax.swing.GroupLayout(pnlDatosExamen);
        pnlDatosExamen.setLayout(pnlDatosExamenLayout);
        pnlDatosExamenLayout.setHorizontalGroup(
            pnlDatosExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosExamenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lowerSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(upperSeparator)
                    .addGroup(pnlDatosExamenLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlDatosExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerfilCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDatosExamenLayout.createSequentialGroup()
                                .addGroup(pnlDatosExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblsLegajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblsAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDatosExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblLegajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        pnlDatosExamenLayout.setVerticalGroup(
            pnlDatosExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosExamenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsAlumno)
                    .addComponent(lblAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsLegajo)
                    .addComponent(lblLegajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPerfilCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        tbpSolapas.setFont(LookAndFeelEntropy.FUENTE_NEGRITA);

        lblsRendidos.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsRendidos.setText("Exámenes Rendidos:");

        lblRendidos.setFont(LookAndFeelEntropy.FUENTE_NEGRITA);
        lblRendidos.setText("30");

        lblsAprobados.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsAprobados.setText("Aprobados / Corregidos:");

        lblAprobados.setFont(LookAndFeelEntropy.FUENTE_NEGRITA);
        lblAprobados.setText("15/30");

        lblsCorregidos.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsCorregidos.setText("Exámenes Corregidos:");

        lblCorregidos.setFont(LookAndFeelEntropy.FUENTE_NEGRITA);
        lblCorregidos.setText("30");

        lblsPorcentajeAprobados.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsPorcentajeAprobados.setText("Porcentaje de aprobados:");

        lblPorcentajeAprobados.setFont(LookAndFeelEntropy.FUENTE_NEGRITA);
        lblPorcentajeAprobados.setText("50%");

        lblsNotaPromedio.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsNotaPromedio.setText("Nota promedio:");

        lblNotaPromedio.setFont(LookAndFeelEntropy.FUENTE_NEGRITA);
        lblNotaPromedio.setText("5");

        lblsNotaMayor.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsNotaMayor.setText("Mayor nota obtenida:");

        lblNotaMayor.setFont(LookAndFeelEntropy.FUENTE_NEGRITA);
        lblNotaMayor.setText("7");

        lblsNotaMenor.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsNotaMenor.setText("Menor nota obtenida:");

        lblNotaMenor.setFont(LookAndFeelEntropy.FUENTE_NEGRITA);
        lblNotaMenor.setText("2");

        javax.swing.GroupLayout pnlGeneralLayout = new javax.swing.GroupLayout(pnlGeneral);
        pnlGeneral.setLayout(pnlGeneralLayout);
        pnlGeneralLayout.setHorizontalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblsNotaMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsNotaMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsNotaPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsPorcentajeAprobados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsRendidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsCorregidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblsAprobados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAprobados, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(lblCorregidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPorcentajeAprobados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNotaPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNotaMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNotaMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlGeneralLayout.setVerticalGroup(
            pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsRendidos)
                    .addComponent(lblRendidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsCorregidos)
                    .addComponent(lblCorregidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsAprobados)
                    .addComponent(lblAprobados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsPorcentajeAprobados)
                    .addComponent(lblPorcentajeAprobados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsNotaPromedio)
                    .addComponent(lblNotaPromedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsNotaMayor)
                    .addComponent(lblNotaMayor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsNotaMenor)
                    .addComponent(lblNotaMenor))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        tbpSolapas.addTab("General", pnlGeneral);

        javax.swing.GroupLayout pnlHistogramaLayout = new javax.swing.GroupLayout(pnlHistograma);
        pnlHistograma.setLayout(pnlHistogramaLayout);
        pnlHistogramaLayout.setHorizontalGroup(
            pnlHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        pnlHistogramaLayout.setVerticalGroup(
            pnlHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        tbpSolapas.addTab("Histograma", pnlHistograma);

        javax.swing.GroupLayout pnlRendimientoLayout = new javax.swing.GroupLayout(pnlRendimiento);
        pnlRendimiento.setLayout(pnlRendimientoLayout);
        pnlRendimientoLayout.setHorizontalGroup(
            pnlRendimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        pnlRendimientoLayout.setVerticalGroup(
            pnlRendimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        tbpSolapas.addTab("Rendimiento", pnlRendimiento);

        scrExamenesRendidos.setBorder(null);

        tblExamenesRendidos.setAutoCreateRowSorter(true);
        tblExamenesRendidos.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        tblExamenesRendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Examen", "Porcentaje de Aprobación", "Fecha", "Objeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExamenesRendidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblExamenesRendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExamenesRendidosMouseClicked(evt);
            }
        });
        scrExamenesRendidos.setViewportView(tblExamenesRendidos);

        lblInfoExamenes.setBackground(LookAndFeelEntropy.COLOR_TABLA_PRIMARIO);
        lblInfoExamenes.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblInfoExamenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_mensajes_informacion_orange.png"))); // NOI18N
        lblInfoExamenes.setText("Hacer doble clic en cada fila para ver la resolución.");
        lblInfoExamenes.setBorder(javax.swing.BorderFactory.createLineBorder(LookAndFeelEntropy.COLOR_ENTROPY));
        lblInfoExamenes.setOpaque(true);

        javax.swing.GroupLayout pnlExamenesLayout = new javax.swing.GroupLayout(pnlExamenes);
        pnlExamenes.setLayout(pnlExamenesLayout);
        pnlExamenesLayout.setHorizontalGroup(
            pnlExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamenesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrExamenesRendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addComponent(lblInfoExamenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlExamenesLayout.setVerticalGroup(
            pnlExamenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrExamenesRendidos, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoExamenes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpSolapas.addTab("Exámenes", pnlExamenes);

        scrClasesAsistidas.setBorder(null);

        tblClasesAsistidas.setAutoCreateRowSorter(true);
        tblClasesAsistidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Presentación", "Descripción", "Fecha", "Objeto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrClasesAsistidas.setViewportView(tblClasesAsistidas);

        javax.swing.GroupLayout pnlAsistenciasLayout = new javax.swing.GroupLayout(pnlAsistencias);
        pnlAsistencias.setLayout(pnlAsistenciasLayout);
        pnlAsistenciasLayout.setHorizontalGroup(
            pnlAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsistenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrClasesAsistidas, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAsistenciasLayout.setVerticalGroup(
            pnlAsistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsistenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrClasesAsistidas, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpSolapas.addTab("Asistencias", pnlAsistencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbpSolapas)
                    .addComponent(pnlDatosExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpSolapas)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblPerfilCompletoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilCompletoMouseClicked
        new DialogPerfilCompleto(VentanaPrincipal.getInstancia(), true, alumno).setVisible(true);
    }//GEN-LAST:event_lblPerfilCompletoMouseClicked

    private void tblExamenesRendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExamenesRendidosMouseClicked
        if (evt.getClickCount() == 2) {
            try {
                Resolucion resolucion = (Resolucion) tblExamenesRendidos.getModel().getValueAt(tblExamenesRendidos.getSelectedRow(), 3);
                if (resolucion != null) {
                    GestorGenerarReporteResolucion gestorReporte = new GestorGenerarReporteResolucion(resolucion);
                    gestorReporte.generarReporteResolucion();
                    String pathArchivo = gestorReporte.getResolucion();
                    Path path = Paths.get(pathArchivo);
                    byte[] pdf = Files.readAllBytes(path);
                    File pdfArchivo = new File(pathArchivo);
                    Desktop.getDesktop().open(pdfArchivo);
                }
            } catch (Exception e) {
                System.err.println("Ocurrió una excepción creando el PDF:  " + e.toString());
            }
        }
    }//GEN-LAST:event_tblExamenesRendidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblAprobados;
    private javax.swing.JLabel lblCorregidos;
    private javax.swing.JLabel lblInfoExamenes;
    private javax.swing.JLabel lblLegajo;
    private javax.swing.JLabel lblNotaMayor;
    private javax.swing.JLabel lblNotaMenor;
    private javax.swing.JLabel lblNotaPromedio;
    private javax.swing.JLabel lblPerfilCompleto;
    private javax.swing.JLabel lblPorcentajeAprobados;
    private javax.swing.JLabel lblRendidos;
    private javax.swing.JLabel lblsAlumno;
    private javax.swing.JLabel lblsAprobados;
    private javax.swing.JLabel lblsCorregidos;
    private javax.swing.JLabel lblsLegajo;
    private javax.swing.JLabel lblsNotaMayor;
    private javax.swing.JLabel lblsNotaMenor;
    private javax.swing.JLabel lblsNotaPromedio;
    private javax.swing.JLabel lblsPorcentajeAprobados;
    private javax.swing.JLabel lblsRendidos;
    private javax.swing.JSeparator lowerSeparator;
    private javax.swing.JPanel pnlAsistencias;
    private javax.swing.JPanel pnlDatosExamen;
    private javax.swing.JPanel pnlExamenes;
    private javax.swing.JPanel pnlGeneral;
    private javax.swing.JPanel pnlHistograma;
    private javax.swing.JPanel pnlRendimiento;
    private javax.swing.JScrollPane scrClasesAsistidas;
    private javax.swing.JScrollPane scrExamenesRendidos;
    private javax.swing.JTable tblClasesAsistidas;
    private javax.swing.JTable tblExamenesRendidos;
    private javax.swing.JTabbedPane tbpSolapas;
    private javax.swing.JSeparator upperSeparator;
    // End of variables declaration//GEN-END:variables
}
