package frontend.tomaexamenes;

import frontend.auxiliares.ComponentMover;
import frontend.auxiliares.LookAndFeelEntropy;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.border.LineBorder;

/**
 *
 * @author Denise
 */
public class DialogCancelarExamen extends javax.swing.JDialog {

    public enum Accion { CANCELAR, CONTINUAR }
    private String strMotivoCancelacion;
    private Accion accionElegida;
    
    /**
     * Constructor de la clase.
     * 
     * @param parent padre del dialog
     * @param modal
     */
    public DialogCancelarExamen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        pnlFondo.setBorder(new LineBorder(new Color(255, 102, 0), 1, true));
        
        this.getRootPane().registerKeyboardAction(new EscapeAction(), 
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        ComponentMover cm = new ComponentMover(JDialog.class, pnlFondo);

        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new PanelGradiente(new Color(235, 204, 114));
        btnCerrar = new javax.swing.JButton();
        scrMotivo = new javax.swing.JScrollPane();
        txaMotivo = new frontend.auxiliares.TextAreaEntropy();
        pnlBotones = new javax.swing.JPanel();
        btnCancelar = new BotonGradiente("Cancelar", new Color(252, 193, 144), new Color(232, 121, 32));
        btnListo = new BotonGradiente("Listo", new Color(252, 193, 144), new Color(232, 121, 32));
        lblMotivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_mensajes_cerrar_advertencia.png"))); // NOI18N
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        txaMotivo.setColumns(20);
        txaMotivo.setRows(5);
        txaMotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txaMotivoKeyReleased(evt);
            }
        });
        scrMotivo.setViewportView(txaMotivo);

        pnlBotones.setLayout(new java.awt.GridLayout(1, 0));

        btnCancelar.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        btnCancelar.setText("Cancelar");
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        btnListo.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        btnListo.setText("Listo");
        btnListo.setContentAreaFilled(false);
        btnListo.setEnabled(false);
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        pnlBotones.add(btnListo);

        lblMotivo.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblMotivo.setText("Describa el motivo de la cancelación:");

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                            .addComponent(lblMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCerrar))
                        .addComponent(scrMotivo)
                        .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlFondoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(scrMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txaMotivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaMotivoKeyReleased
        btnListo.setEnabled(!txaMotivo.getText().trim().isEmpty());
        strMotivoCancelacion = txaMotivo.getText().trim();
    }//GEN-LAST:event_txaMotivoKeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.accionElegida = Accion.CANCELAR;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        this.accionElegida = Accion.CONTINUAR;
        this.dispose();
    }//GEN-LAST:event_btnListoActionPerformed

    public String getStrMotivoCancelacion() {
        return strMotivoCancelacion;
    }

    public Accion getAccionElegida() {
        return accionElegida;
    }

    
    /**
     * Representa un panel con fondo de gradiente.
     */
    private class PanelGradiente extends JPanel {

        private Color color;

        /**
         * Constructor de la clase.
         *
         * @param color el gradiente comenzará en blanco hasta el color pasado
         * por parámetro, desde arriba hacia abajo.
         */
        public PanelGradiente(Color color) {
            this.color = color;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            int h = getHeight();
            int w = getWidth();

            GradientPaint gradientPaint = new GradientPaint(0, 0, Color.WHITE, 0, h, color);

            Graphics2D g2D = (Graphics2D) g;
            g2D.setPaint(gradientPaint);
            g2D.fillRect(0, 0, w, h);
            repaint();
        }

        /**
         * Modifica el color de gradiente del panel.
         *
         * @param color nuevo color.
         */
        public void setColor(Color color) {
            this.color = color;
            this.repaint();
        }

    }

    /**
     * Representa un botón con fondo de gradiente.
     */
    private class BotonGradiente extends JButton {

        private Color color1, color2;

        /**
         * Constructor de la clase.
         *
         * @param strTexto texto a mostrarse en el botón.
         * @param color1 color del margen superior.
         * @param color2 color del margen inferior.
         */
        public BotonGradiente(String strTexto, Color color1, Color color2) {
            super.setText(strTexto);
            this.color1 = color1;
            this.color2 = color2;
        }

        @Override
        protected void paintComponent(Graphics g) {

            int h = getHeight();
            int w = getWidth();

            GradientPaint gradientPaint = new GradientPaint(0, 0, color1, 0, h, color2);

            Graphics2D g2D = (Graphics2D) g;
            g2D.setPaint(gradientPaint);
            g2D.fillRect(0, 0, w, h);

            super.paintComponent(g);
        }

        /**
         * Modifica el color de gradiente del botón.
         *
         * @param color1 color del margen superior.
         * @param color2 color del margen inferior.
         */
        public void setColor(Color color1, Color color2) {
            this.color1 = color1;
            this.color2 = color2;
            this.repaint();
        }

    }
    
    /**
     * Clase que escucha por el tecleo de la tecla Esc.
     */
    private class EscapeAction implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnListo;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JScrollPane scrMotivo;
    private frontend.auxiliares.TextAreaEntropy txaMotivo;
    // End of variables declaration//GEN-END:variables
}
