package frontend.presentacion;

import frontend.examenes.*;
import backend.auxiliares.Mensajes;
import backend.gestores.GestorPresentacion;
import frontend.auxiliares.LookAndFeelEntropy;
import frontend.inicio.VentanaPrincipal;
import frontend.usuario.DialogInfoUsuario;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Clase que representa al panel que anuncia la recepción del objeto examen y
 * permite al alumno dar comienzo al mismo.
 *
 * @author Denise
 */
public class PanelIniciarPresentacion extends javax.swing.JPanel {

    private final GestorPresentacion gestor;

    /**
     * Constructor de la clase.
     *
     * @param gestor gestor de la toma de exámenes que maneja el proceso.
     */
    public PanelIniciarPresentacion(GestorPresentacion gestor) {
        initComponents();
        this.gestor = gestor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlDatosExamen = new javax.swing.JPanel();
        pnlDescripcion = new javax.swing.JPanel();
        btnVerDatosProfesor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlDatosProfesor = new javax.swing.JPanel();
        btnComenzar = new javax.swing.JButton();

        pnlFondo.setLayout(new java.awt.GridLayout(0, 1));

        pnlSuperior.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        lblTitulo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 102, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("¡Existe una clase a la cual unirse!");
        pnlSuperior.add(lblTitulo);

        pnlDatosExamen.setLayout(new javax.swing.BoxLayout(pnlDatosExamen, javax.swing.BoxLayout.Y_AXIS));

        pnlDescripcion.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        btnVerDatosProfesor.setBackground(new java.awt.Color(255, 153, 51));
        btnVerDatosProfesor.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnVerDatosProfesor.setForeground(new java.awt.Color(204, 102, 0));
        btnVerDatosProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_perfil_profesor_50x50.png"))); // NOI18N
        btnVerDatosProfesor.setText("<html>Ver datos del profesor</html>");
        btnVerDatosProfesor.setContentAreaFilled(false);
        btnVerDatosProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerDatosProfesor.setFocusPainted(false);
        btnVerDatosProfesor.setIconTextGap(10);
        btnVerDatosProfesor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_perfil_profesor_60x60.png"))); // NOI18N
        btnVerDatosProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatosProfesorActionPerformed(evt);
            }
        });
        pnlDescripcion.add(btnVerDatosProfesor);

        pnlDatosExamen.add(pnlDescripcion);

        pnlSuperior.add(pnlDatosExamen);

        pnlFondo.add(pnlSuperior);

        jPanel1.setMaximumSize(new java.awt.Dimension(112, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(112, 35));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(112, 35));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlDatosProfesor.setOpaque(false);
        pnlDatosProfesor.setPreferredSize(new java.awt.Dimension(364, 100));

        btnComenzar.setBackground(new java.awt.Color(255, 153, 51));
        btnComenzar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnComenzar.setForeground(new java.awt.Color(204, 102, 0));
        btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_comenzar.png"))); // NOI18N
        btnComenzar.setText("<html>Comenzar</html>");
        btnComenzar.setBorder(null);
        btnComenzar.setContentAreaFilled(false);
        btnComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComenzar.setIconTextGap(10);
        btnComenzar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_comenzar_50x50.png"))); // NOI18N
        btnComenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComenzarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComenzarMouseExited(evt);
            }
        });
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosProfesorLayout = new javax.swing.GroupLayout(pnlDatosProfesor);
        pnlDatosProfesor.setLayout(pnlDatosProfesorLayout);
        pnlDatosProfesorLayout.setHorizontalGroup(
            pnlDatosProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnComenzar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
        pnlDatosProfesorLayout.setVerticalGroup(
            pnlDatosProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProfesorLayout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlDatosProfesor, java.awt.BorderLayout.PAGE_START);

        pnlFondo.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        try {
            this.gestor.comenzarPresentacion();
        } catch (IOException ex) {
            Logger.getLogger(PanelIniciarPresentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnVerDatosProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatosProfesorActionPerformed
        new DialogInfoUsuario(VentanaPrincipal.getInstancia(), true, this.gestor.getProfesor()).setVisible(true);
    }//GEN-LAST:event_btnVerDatosProfesorActionPerformed

    private void btnComenzarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComenzarMouseEntered
        btnComenzar.setText("<html><u>Comenzar</u></html>");
    }//GEN-LAST:event_btnComenzarMouseEntered

    private void btnComenzarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComenzarMouseExited
        btnComenzar.setText("<html>Comenzar</html>");
    }//GEN-LAST:event_btnComenzarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnVerDatosProfesor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlDatosExamen;
    private javax.swing.JPanel pnlDatosProfesor;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables
}
