/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.presentaciones;

import backend.auxiliares.Mensajes;
import backend.dao.diseños.DAOCurso;
import backend.dao.diseños.DAOInstitucion;
import backend.diseños.Curso;
import backend.diseños.Institucion;
import frontend.auxiliares.LookAndFeelEntropy;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jose
 */
public class DialogGuardarAsistencia extends javax.swing.JDialog {
   private final FrameControlPresentaciones mPadre;
   private DAOInstitucion daoInstitucion = new DAOInstitucion();
   private DAOCurso daoCurso = new DAOCurso();
    /**
     * Creates new form DialogGuardarAsistencia
     */
    public DialogGuardarAsistencia(java.awt.Frame mPadre, boolean modal) {
        super(mPadre, modal);
        initComponents();
        this.mPadre = (FrameControlPresentaciones) mPadre;
        setLocationRelativeTo(null);
        setTitle("Guardar presentación");
        cargarComboInstituciones();
        cargarComboCursos(((Institucion)cmbInstitucion.getSelectedItem()).getIntInstitucionId());
    }
    
    private void cargarComboInstituciones()
    {
        DAOInstitucion daoInstitucion = new DAOInstitucion();
        ArrayList<Institucion>listaInstituciones = daoInstitucion.recuperarTodasLasInstituciones("");
        
        DefaultComboBoxModel modeloCombo= new DefaultComboBoxModel();
        for (Institucion institucion : listaInstituciones) 
        {
            modeloCombo.addElement(institucion);
            
        }
       cmbInstitucion.setModel(modeloCombo);
    }
    private void cargarComboCursos(int idInstitucion)
    {
        DAOCurso daoCurso= new DAOCurso();
        Institucion institucion = daoInstitucion.recuperarInstitucion(idInstitucion);
        ArrayList<Curso>listacurso = daoCurso.recuperarTodosLosCursos(institucion,"");
        DefaultComboBoxModel modeloCombo= new DefaultComboBoxModel();
        for (Curso curso : listacurso) 
        {
            modeloCombo.addElement(curso);
            
        }
       cmbCurso.setModel(modeloCombo);
    }
        
        
       /* private boolean guardarClase()
        {
            Presentacion presentacion= new Presentacion();
            presentacion.setDateFecha(new Date().getTime());
            presentacion.setIntIdCurso(((Curso)cbCurso.getSelectedItem()).getIntCursoId());
            presentacion.setStrNombre(txtNombreClase.getText())
            prsentacion.setStrDecripcion(txtDescripcion.getText());
            return DAOPresentacion.guardarClase(presentacion);
        }
        */
        private boolean validarCampos()
        {
            if(txtNombreClase.equals(""))
            {
                Mensajes.mostrarAdvertencia("La clase necesita un nombre");
                return false;
            }
            return true;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosClase = new javax.swing.JPanel();
        lblInstitucion = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblNombreClase = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtNombreClase = new frontend.auxiliares.TextFieldEntropy();
        cmbInstitucion = new javax.swing.JComboBox();
        cmbCurso = new javax.swing.JComboBox();
        scrDescripcion = new javax.swing.JScrollPane();
        txaDescripcion = new frontend.auxiliares.TextAreaEntropy();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDatosClase.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la presentación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        pnlDatosClase.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        pnlDatosClase.setMinimumSize(pnlDatosClase.getPreferredSize());

        lblInstitucion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblInstitucion.setText("Institución:");

        lblCurso.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblCurso.setText("Curso:");

        pnlBotones.setLayout(new java.awt.GridLayout(1, 0));

        btnRegresar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_volver.png"))); // NOI18N
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setIconTextGap(10);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnRegresar);

        btnGuardar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_guardar.png"))); // NOI18N
        btnGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setIconTextGap(10);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnGuardar);

        lblNombreClase.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblNombreClase.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreClase.setText("Título de la clase:");

        lblDescripcion.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescripcion.setText("Descripción:");

        txtNombreClase.setTextoPorDefecto("Ingrese un título...");
        txtNombreClase.mostrarTextoPorDefecto();

        cmbInstitucion.setBackground(new java.awt.Color(255, 204, 102));
        cmbInstitucion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cmbInstitucion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbInstitucionItemStateChanged(evt);
            }
        });

        cmbCurso.setBackground(new java.awt.Color(255, 204, 102));
        cmbCurso.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        scrDescripcion.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txaDescripcion.setTextoPorDefecto("Ingrese una descripción...");
        txaDescripcion.mostrarTextoPorDefecto();
        txaDescripcion.setColumns(20);
        txaDescripcion.setRows(2);
        scrDescripcion.setViewportView(txaDescripcion);

        javax.swing.GroupLayout pnlDatosClaseLayout = new javax.swing.GroupLayout(pnlDatosClase);
        pnlDatosClase.setLayout(pnlDatosClaseLayout);
        pnlDatosClaseLayout.setHorizontalGroup(
            pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosClaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDatosClaseLayout.createSequentialGroup()
                        .addGroup(pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblInstitucion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreClase, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbInstitucion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlDatosClaseLayout.setVerticalGroup(
            pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosClaseLayout.createSequentialGroup()
                .addGroup(pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblInstitucion)
                    .addComponent(cmbInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreClase)
                    .addComponent(txtNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosClaseLayout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatosClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(validarCampos())
        {
            //guardarClase();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbInstitucionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbInstitucionItemStateChanged
        cargarComboCursos(((Institucion)cmbInstitucion.getSelectedItem()).getIntInstitucionId());
    }//GEN-LAST:event_cmbInstitucionItemStateChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox cmbCurso;
    private javax.swing.JComboBox cmbInstitucion;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblInstitucion;
    private javax.swing.JLabel lblNombreClase;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatosClase;
    private javax.swing.JScrollPane scrDescripcion;
    private frontend.auxiliares.TextAreaEntropy txaDescripcion;
    private frontend.auxiliares.TextFieldEntropy txtNombreClase;
    // End of variables declaration//GEN-END:variables
}
