/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.presentaciones;

import backend.auxiliares.Mensajes;
import backend.dao.diseños.DAOCurso;
import backend.dao.diseños.DAOInstitucion;
import backend.diseños.Curso;
import backend.diseños.Institucion;
import backend.reporte.GestorGenerarReportePresentacionesRealizadas;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Jose
 */
public class DialogAdministrarClasesDictadas extends javax.swing.JDialog {

    private DAOInstitucion daoInstitucion = new DAOInstitucion();
    private DAOCurso daoCurso = new DAOCurso();

    /**
     * Creates new form DialogAdministrarClasesDictadas
     */
    public DialogAdministrarClasesDictadas(java.awt.Frame parent, boolean modal) {
        super(parent, false);
        initComponents();
        cargarComboInstituciones();
        cargarComboCursos(((Institucion) cbInstitucion.getSelectedItem()).getIntInstitucionId());
    }

    private void cargarComboInstituciones() {
        DAOInstitucion daoInstitucion = new DAOInstitucion();
        ArrayList<Institucion> listaInstituciones = daoInstitucion.recuperarTodasLasInstituciones("");
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        for (Institucion institucion : listaInstituciones) {
            modeloCombo.addElement(institucion);
        }
        cbInstitucion.setModel(modeloCombo);
    }

    private void cargarComboCursos(int idInstitucion) {
        DAOCurso daoCurso = new DAOCurso();
        Institucion institucion = daoInstitucion.recuperarInstitucion(idInstitucion);
        ArrayList<Curso> listacurso = daoCurso.recuperarTodosLosCursos(institucion, "");
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        for (Curso curso : listacurso) {
            modeloCombo.addElement(curso);

        }
        cbCurso.setModel(modeloCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbCurso = new javax.swing.JComboBox();
        cbInstitucion = new javax.swing.JComboBox();
        lblInstitucion = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        dcFechaDesde = new com.toedter.calendar.JDateChooser();
        lblFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsClasesDictadas = new javax.swing.JList();
        btnGuardarAsistencia1 = new javax.swing.JButton();
        dcFechaHasta = new com.toedter.calendar.JDateChooser();
        lblFecha1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnGuardarAsistencia2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clases Dictadas"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 65, 350, -1));

        cbInstitucion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbInstitucion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbInstitucionItemStateChanged(evt);
            }
        });
        jPanel1.add(cbInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 27, 350, -1));

        lblInstitucion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInstitucion.setText("Insitutucion:");
        jPanel1.add(lblInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, 70, -1));

        lblCurso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCurso.setText("Curso:");
        jPanel1.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 68, 70, -1));

        dcFechaDesde.setDate(new Date());
        jPanel1.add(dcFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 130, -1));

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("Fecha desde:");
        jPanel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        jScrollPane1.setViewportView(lsClasesDictadas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 470, 280));

        btnGuardarAsistencia1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnGuardarAsistencia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_examinar_25x25.png"))); // NOI18N
        btnGuardarAsistencia1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGuardarAsistencia1.setContentAreaFilled(false);
        btnGuardarAsistencia1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarAsistencia1.setIconTextGap(10);
        btnGuardarAsistencia1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarAsistencia1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarAsistencia1MouseExited(evt);
            }
        });
        btnGuardarAsistencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAsistencia1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarAsistencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 197, -1));

        dcFechaHasta.setDate(new Date());
        jPanel1.add(dcFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 130, -1));

        lblFecha1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha1.setText("Fecha hasta:");
        jPanel1.add(lblFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 90, -1));

        btnRegresar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_volver.png"))); // NOI18N
        btnRegresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setIconTextGap(10);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGuardarAsistencia2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnGuardarAsistencia2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_imprimir_25x25.png"))); // NOI18N
        btnGuardarAsistencia2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGuardarAsistencia2.setContentAreaFilled(false);
        btnGuardarAsistencia2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarAsistencia2.setIconTextGap(10);
        btnGuardarAsistencia2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarAsistencia2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarAsistencia2MouseExited(evt);
            }
        });
        btnGuardarAsistencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAsistencia2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarAsistencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarAsistencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbInstitucionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbInstitucionItemStateChanged
        cargarComboCursos(((Institucion) cbInstitucion.getSelectedItem()).getIntInstitucionId());
    }//GEN-LAST:event_cbInstitucionItemStateChanged

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarAsistencia1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarAsistencia1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAsistencia1MouseEntered

    private void btnGuardarAsistencia1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarAsistencia1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAsistencia1MouseExited

    private void btnGuardarAsistencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsistencia1ActionPerformed
      if(validarFechas())
      {
          //buscarClasesDictadas();
      }
    }//GEN-LAST:event_btnGuardarAsistencia1ActionPerformed

    private void btnGuardarAsistencia2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarAsistencia2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAsistencia2MouseEntered

    private void btnGuardarAsistencia2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarAsistencia2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAsistencia2MouseExited

    
    /*private ArrayList<Presentacion> buscarClasesDictadas()
    {
     return null;
    }*/
    
    private boolean validarSeleccion()
    {
        if(lsClasesDictadas.getSelectedValue()!=null)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    
    private boolean validarFechas()
    {
        if(dcFechaDesde==null)
        {
            Mensajes.mostrarError("Debe elegir una Fecha desde valida");
            return false;
        }
        if(dcFechaHasta==null)
        {
            Mensajes.mostrarError("Debe elegir una fecha hasta valida");
            return false;
        }
        return true;
    }
    
    private void btnGuardarAsistencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsistencia2ActionPerformed
        try {
            if(!validarSeleccion())
            {
             String institucion = ((Institucion)cbInstitucion.getSelectedItem()).getStrNombre();
             String curso = ((Curso)cbCurso.getSelectedItem()).getStrNombre();
            //Presentacion presentacion = new Presentacion();    
            GestorGenerarReportePresentacionesRealizadas.reportePresentacionRealizada(institucion, curso);
            }
            else
            {
                Mensajes.mostrarError("Debe seleccionar algun clase dictada de la ");
            }
        } catch (JRException ex) {
            Logger.getLogger(DialogAdministrarClasesDictadas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarAsistencia2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAdministrarClasesDictadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAdministrarClasesDictadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAdministrarClasesDictadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAdministrarClasesDictadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAdministrarClasesDictadas dialog = new DialogAdministrarClasesDictadas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAsistencia1;
    private javax.swing.JButton btnGuardarAsistencia2;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JComboBox cbInstitucion;
    private com.toedter.calendar.JDateChooser dcFechaDesde;
    private com.toedter.calendar.JDateChooser dcFechaHasta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblInstitucion;
    private javax.swing.JList lsClasesDictadas;
    // End of variables declaration//GEN-END:variables
}
