package frontend.inicio;


/**
 * Clase que representa el Panel de apertura del sistema en el módulo del
 * profesor.
 *
 * @author Denise
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form InitPanel
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEntropy = new javax.swing.JLabel();

        setOpaque(false);

        lblEntropy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntropy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_entropy.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntropy, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblEntropy, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        getAccessibleContext().setAccessibleName("Inicio");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEntropy;
    // End of variables declaration//GEN-END:variables
}
