package frontend.examenes;

import backend.auxiliares.Mensajes;
import backend.gestores.GestorResolucionExamen;
import backend.usuarios.Alumno;
import frontend.auxiliares.LookAndFeelEntropy;
import frontend.inicio.VentanaPrincipal;
import frontend.usuario.DialogInfoUsuario;
import java.io.IOException;

/**
 * Clase que representa al panel que anuncia la recepción del objeto examen y
 * permite al alumno dar comienzo al mismo.
 *
 * @author Denise
 */
public class PanelIniciarExamen extends javax.swing.JPanel {

    private final GestorResolucionExamen gestor;

    /**
     * Constructor de la clase.
     *
     * @param gestor gestor de la toma de exámenes que maneja el proceso.
     */
    public PanelIniciarExamen(GestorResolucionExamen gestor) {
        initComponents();
        this.gestor = gestor;
        lblExamen.setText(gestor.getExamen().getStrNombre());
        lblDescripcion.setText(gestor.getExamen().getStrDescripcion());
        int intHoras = gestor.getExamen().getIntTiempo() / 60;
        int intMinutos = gestor.getExamen().getIntTiempo() % 60;
        String strDuracion = String.format("%02d", intHoras) + ":" + String.format("%02d", intMinutos) + " hs.";
        lblDuracion.setText(strDuracion);
        //jPanel1.removeAll();
        //jPanel1.add(btnComenzar, java.awt.BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlDatosExamen = new javax.swing.JPanel();
        pnlNombre = new javax.swing.JPanel();
        lblsExamen = new javax.swing.JLabel();
        lblExamen = new javax.swing.JLabel();
        pnlDescripcion = new javax.swing.JPanel();
        lblsDescripcion = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        pnlDuracion = new javax.swing.JPanel();
        lblsDuracion = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        pnlCodigo = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnComenzar = new javax.swing.JButton();
        pnlDatosProfesor = new javax.swing.JPanel();
        btnVerDatosProfesor = new javax.swing.JButton();

        pnlFondo.setLayout(new java.awt.GridLayout(0, 1));

        pnlSuperior.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        lblTitulo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 102, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("¡Existe un examen en espera!");
        pnlSuperior.add(lblTitulo);

        pnlDatosExamen.setLayout(new javax.swing.BoxLayout(pnlDatosExamen, javax.swing.BoxLayout.Y_AXIS));

        pnlNombre.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        lblsExamen.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsExamen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsExamen.setText("Examen:");
        pnlNombre.add(lblsExamen);

        lblExamen.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblExamen.setText("Primer Parcial IA");
        pnlNombre.add(lblExamen);

        pnlDatosExamen.add(pnlNombre);

        pnlDescripcion.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        lblsDescripcion.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsDescripcion.setText("Descripción:");
        lblsDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlDescripcion.add(lblsDescripcion);

        lblDescripcion.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblDescripcion.setText("Ajustar altura al cargar el texto.");
        lblDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlDescripcion.add(lblDescripcion);

        pnlDatosExamen.add(pnlDescripcion);

        pnlDuracion.setLayout(new java.awt.GridLayout(1, 0, 30, 0));

        lblsDuracion.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblsDuracion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblsDuracion.setText("Duración:");
        lblsDuracion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlDuracion.add(lblsDuracion);

        lblDuracion.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblDuracion.setText("1:00 hs");
        lblDuracion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlDuracion.add(lblDuracion);

        pnlDatosExamen.add(pnlDuracion);

        pnlCodigo.setLayout(new java.awt.GridLayout());

        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCodigo.setText("Codigo:     ");
        pnlCodigo.add(lblCodigo);

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        pnlCodigo.add(txtCodigo);

        pnlDatosExamen.add(pnlCodigo);

        pnlSuperior.add(pnlDatosExamen);

        pnlFondo.add(pnlSuperior);

        jPanel1.setMaximumSize(new java.awt.Dimension(112, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(112, 35));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(112, 35));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnComenzar.setBackground(new java.awt.Color(255, 153, 51));
        btnComenzar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        btnComenzar.setForeground(new java.awt.Color(204, 102, 0));
        btnComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_comenzar.png"))); // NOI18N
        btnComenzar.setText("<html>Comenzar</html>");
        btnComenzar.setBorder(null);
        btnComenzar.setContentAreaFilled(false);
        btnComenzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComenzar.setIconTextGap(10);
        btnComenzar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_comenzar_50x50.png"))); // NOI18N
        btnComenzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComenzarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComenzarMouseExited(evt);
            }
        });
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComenzar, java.awt.BorderLayout.CENTER);

        pnlDatosProfesor.setOpaque(false);
        pnlDatosProfesor.setPreferredSize(new java.awt.Dimension(364, 100));

        btnVerDatosProfesor.setBackground(new java.awt.Color(255, 153, 51));
        btnVerDatosProfesor.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        btnVerDatosProfesor.setForeground(new java.awt.Color(204, 102, 0));
        btnVerDatosProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_perfil_profesor_50x50.png"))); // NOI18N
        btnVerDatosProfesor.setText("<html>Ver datos del profesor</html>");
        btnVerDatosProfesor.setContentAreaFilled(false);
        btnVerDatosProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerDatosProfesor.setFocusPainted(false);
        btnVerDatosProfesor.setIconTextGap(10);
        btnVerDatosProfesor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/ic_perfil_profesor_60x60.png"))); // NOI18N
        btnVerDatosProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDatosProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosProfesorLayout = new javax.swing.GroupLayout(pnlDatosProfesor);
        pnlDatosProfesor.setLayout(pnlDatosProfesorLayout);
        pnlDatosProfesorLayout.setHorizontalGroup(
            pnlDatosProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerDatosProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDatosProfesorLayout.setVerticalGroup(
            pnlDatosProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosProfesorLayout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(btnVerDatosProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(pnlDatosProfesor, java.awt.BorderLayout.PAGE_START);

        pnlFondo.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        try {
            String codigo = this.txtCodigo.getText();
            this.gestor.comenzarExamen(codigo);
        } catch (IOException ioe) {
            Mensajes.mostrarError("Imposible avisar comienzo al profesor.");
        }
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnVerDatosProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDatosProfesorActionPerformed
        new DialogInfoUsuario(VentanaPrincipal.getInstancia(), true, this.gestor.getProfesor()).setVisible(true);
    }//GEN-LAST:event_btnVerDatosProfesorActionPerformed

    private void btnComenzarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComenzarMouseEntered
        btnComenzar.setText("<html><u>Comenzar</u></html>");
    }//GEN-LAST:event_btnComenzarMouseEntered

    private void btnComenzarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComenzarMouseExited
        btnComenzar.setText("<html>Comenzar</html>");
    }//GEN-LAST:event_btnComenzarMouseExited

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnVerDatosProfesor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblExamen;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblsDescripcion;
    private javax.swing.JLabel lblsDuracion;
    private javax.swing.JLabel lblsExamen;
    private javax.swing.JPanel pnlCodigo;
    private javax.swing.JPanel pnlDatosExamen;
    private javax.swing.JPanel pnlDatosProfesor;
    private javax.swing.JPanel pnlDescripcion;
    private javax.swing.JPanel pnlDuracion;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlNombre;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
