package frontend.examenes;

import frontend.inicio.VentanaPrincipal;

/**
 *
 * @author Denise
 */
public class PanelEspera extends javax.swing.JPanel {

    private final VentanaPrincipal mPadre;
    
    /**
     * Constructor de la clase.
     * 
     * @param padre
     */
    public PanelEspera(VentanaPrincipal padre) {
        this.mPadre = padre;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEspera = new javax.swing.JLabel();

        lblEspera.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblEspera.setForeground(new java.awt.Color(204, 102, 0));
        lblEspera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEspera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/imagenes/cargador.gif"))); // NOI18N
        lblEspera.setText("Estableciendo conexión con el profesor...");
        lblEspera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblEspera.setIconTextGap(25);
        lblEspera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEspera, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEspera, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEspera;
    // End of variables declaration//GEN-END:variables
}
