package frontend.diseños;

import frontend.auxiliares.LookAndFeelEntropy;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 * Clase que representa el panel de edición de preguntas numéricas.
 * 
 * @author Denise
 */
public class PanelPreguntaNumerica extends javax.swing.JPanel {

    /**
     * Constructor por defecto de la clase.
     */
    public PanelPreguntaNumerica() {
        initComponents();
        rbnNumero.grabFocus();
        this.habilitarNumeroRango();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrRespuestaCorrecta = new javax.swing.ButtonGroup();
        rbnNumero = new javax.swing.JRadioButton();
        rbnRango = new javax.swing.JRadioButton();
        spnNumero = new javax.swing.JSpinner();
        lblDecimales = new javax.swing.JLabel();
        spnDecimales = new javax.swing.JSpinner();
        lblDesde = new javax.swing.JLabel();
        lblHasta = new javax.swing.JLabel();
        spnDesde = new javax.swing.JSpinner();
        spnHasta = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Respuesta Correcta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12), java.awt.Color.black)); // NOI18N

        bgrRespuestaCorrecta.add(rbnNumero);
        rbnNumero.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        rbnNumero.setSelected(true);
        rbnNumero.setText("Número");
        rbnNumero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbnNumeroItemStateChanged(evt);
            }
        });

        bgrRespuestaCorrecta.add(rbnRango);
        rbnRango.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        rbnRango.setText("Rango");

        spnNumero.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        spnNumero.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.1d)));
        JTextField tf = ((JSpinner.DefaultEditor) spnNumero.getEditor()).getTextField();
        tf.setCaretColor(LookAndFeelEntropy.COLOR_CURSOR);
        tf.setSelectionColor(LookAndFeelEntropy.COLOR_SELECCION_TEXTO);

        lblDecimales.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblDecimales.setText("Variación aceptada:   ±");

        spnDecimales.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        spnDecimales.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.1d)));
        JTextField txtDecimalesEditor = ((JSpinner.DefaultEditor) spnDecimales.getEditor()).getTextField();
        txtDecimalesEditor.setCaretColor(LookAndFeelEntropy.COLOR_CURSOR);
        txtDecimalesEditor.setSelectionColor(LookAndFeelEntropy.COLOR_SELECCION_TEXTO);

        lblDesde.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblDesde.setText("Desde:");

        lblHasta.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        lblHasta.setText("Hasta:");

        spnDesde.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        spnDesde.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.1d)));
        JTextField txtDesdeEditor = ((JSpinner.DefaultEditor) spnDesde.getEditor()).getTextField();
        txtDesdeEditor.setCaretColor(LookAndFeelEntropy.COLOR_CURSOR);
        txtDesdeEditor.setSelectionColor(LookAndFeelEntropy.COLOR_SELECCION_TEXTO);

        spnHasta.setFont(LookAndFeelEntropy.FUENTE_REGULAR);
        spnHasta.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(0.1d)));
        JTextField txtHastaEditor = ((JSpinner.DefaultEditor) spnHasta.getEditor()).getTextField();
        txtHastaEditor.setCaretColor(LookAndFeelEntropy.COLOR_CURSOR);
        txtHastaEditor.setSelectionColor(LookAndFeelEntropy.COLOR_SELECCION_TEXTO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDecimales, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnDecimales, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rbnRango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbnNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(lblHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnDesde)
                                    .addComponent(spnHasta)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnNumero))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnNumero)
                    .addComponent(spnNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnRango)
                    .addComponent(lblDesde)
                    .addComponent(spnDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDecimales)
                    .addComponent(spnDecimales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbnNumeroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbnNumeroItemStateChanged
        this.habilitarNumeroRango();
    }//GEN-LAST:event_rbnNumeroItemStateChanged
    
    public boolean getEsRango() {
        return rbnRango.isSelected();
    }
    
    public double getNumero() {
        return Double.parseDouble(spnNumero.getModel().getValue().toString());
    }
    
    public double getRangoDesde() {
        return Double.parseDouble(spnDesde.getModel().getValue().toString());
    }
    
    public double getRangoHasta() {
        return Double.parseDouble(spnHasta.getModel().getValue().toString());
    }
    
    public double getVariacion() {
        return Double.parseDouble(spnDecimales.getModel().getValue().toString());
    }
    
    public void setValores(boolean blnEsRango, double dblNumero, double dblRangoDesde, double dblRangoHasta, double dblVariacion) {
        if(blnEsRango) {
            rbnRango.setSelected(true);
            rbnNumero.setSelected(false);
            spnDesde.getModel().setValue(dblRangoDesde);
            spnHasta.getModel().setValue(dblRangoHasta);
        } else {
            rbnRango.setSelected(false);
            rbnNumero.setSelected(true);
            spnNumero.getModel().setValue(dblNumero);
        }
        spnDecimales.getModel().setValue(dblVariacion);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrRespuestaCorrecta;
    private javax.swing.JLabel lblDecimales;
    private javax.swing.JLabel lblDesde;
    private javax.swing.JLabel lblHasta;
    private javax.swing.JRadioButton rbnNumero;
    private javax.swing.JRadioButton rbnRango;
    private javax.swing.JSpinner spnDecimales;
    private javax.swing.JSpinner spnDesde;
    private javax.swing.JSpinner spnHasta;
    private javax.swing.JSpinner spnNumero;
    // End of variables declaration//GEN-END:variables

    private void habilitarNumeroRango() {
        if (rbnNumero.isSelected()) {
            spnNumero.setEnabled(true);
            spnNumero.setValue(0);
            lblDesde.setEnabled(false);
            lblHasta.setEnabled(false);
            spnDesde.setEnabled(false);
            spnDesde.setValue(0);
            spnHasta.setEnabled(false);
            spnHasta.setValue(0);
        } else {
            spnNumero.setEnabled(false);
            spnNumero.setValue(0);
            lblDesde.setEnabled(true);
            lblHasta.setEnabled(true);
            spnDesde.setEnabled(true);
            spnDesde.setValue(0);
            spnHasta.setEnabled(true);
            spnHasta.setValue(0);
        }
    }
}
